export interface ICaderno {
  id_rosto: number;
  nome: string;
  morada: string;
  nif: string;
  nifap: string;
  codig_postal: string;
  localizacao: string;
  concelho: string;
  freguesia: string;
  telefone: number;
  telemovel: number;
  email: string;
  cargo: string;
  nome_S: string;
  morada_S: string;
  telefone_S: number;
  telemovel_S: number;
  email_S: string;
  local_sede_E: string;
  codigo_postal_E: string;
  freguesia_E: string;
  concelho_E: string;
  designacao_baldio: string;
  n_parcelario: string;
  n_subparcela: string;
  localizacao_baldio: string;
  concelho_baldio: string;
  freguesia_baldio: string;
  area_manutencao_AB: string;
  area_conversao_AB: string;
  area_PRODI: string;
  area_total_exploracao: string;
  transformacao: boolean;
  tranform_obs: string;
  regante_classe_A: boolean;
  regante_classe_B_plus: boolean;
  regante_classe_B: boolean;
  area_regada: string;
  titulo_regante: string;
  data_contrato_ERR: string;
  bovinos_conversao_AB: string;
  bovinos_manutencao_AB: string;
  ovinos_conversao_AB: string;
  ovinos_manutencao_AB: string;
  caprinos_conversao_AB: string;
  caprinos_manutencao_AB: string;
  outras_espe_conver_AB: string;
  outras_esp_manu_AB: string;
  bovinos_PRODI: string;
  ovinos_PRODI: string;
  caprinos_PRODI: string;
  outras_esp_PRODI: string;
  assistencia_tec_AB: string;
  assistencia_tec_PRODI: string;
  assistencia_tec_past_permanente: string;
  indentificacao_OC_AB: string;
  indentificacao_OC_PRODI: string;
  indentificacao_OC_PP_biod: string;
  identificacao_ERR: string;
  drap: string;
  ano: number;
  activo: number;
  id_agri: number;
  last_update: string;
  create_date: string;
  uuid: string;
}

export let TCaderno = {
  id_rosto: 'number',
  nome: 'string',
  morada: 'string',
  nif: 'string',
  nifap: 'string',
  codig_postal: 'string',
  localizacao: 'string',
  concelho: 'string',
  freguesia: 'string',
  telefone: 'number',
  telemovel: 'number',
  email: 'string',
  cargo: 'string',
  nome_S: 'string',
  morada_S: 'string',
  telefone_S: 'number',
  telemovel_S: 'number',
  email_S: 'string',
  local_sede_E: 'string',
  codigo_postal_E: 'string',
  freguesia_E: 'string',
  concelho_E: 'string',
  designacao_baldio: 'string',
  n_parcelario: 'string',
  n_subparcela: 'string',
  localizacao_baldio: 'string',
  concelho_baldio: 'string',
  freguesia_baldio: 'string',
  area_manutencao_AB: 'string',
  area_conversao_AB: 'string',
  area_PRODI: 'string',
  area_total_exploracao: 'string',
  transformacao: 'boolean',
  tranform_obs: 'string',
  regante_classe_A: 'boolean',
  regante_classe_B_plus: 'boolean',
  regante_classe_B: 'boolean',
  area_regada: 'string',
  titulo_regante: 'string',
  data_contrato_ERR: 'string',
  bovinos_conversao_AB: 'string',
  bovinos_manutencao_AB: 'string',
  ovinos_conversao_AB: 'string',
  ovinos_manutencao_AB: 'string',
  caprinos_conversao_AB: 'string',
  caprinos_manutencao_AB: 'string',
  outras_espe_conver_AB: 'string',
  outras_esp_manu_AB: 'string',
  bovinos_PRODI: 'string',
  ovinos_PRODI: 'string',
  caprinos_PRODI: 'string',
  outras_esp_PRODI: 'string',
  assistencia_tec_AB: 'string',
  assistencia_tec_PRODI: 'string',
  assistencia_tec_past_permanente: 'string',
  indentificacao_OC_AB: 'string',
  indentificacao_OC_PRODI: 'string',
  indentificacao_OC_PP_biod: 'string',
  identificacao_ERR: 'string',
  drap: 'string',
  ano: 'number',
  activo: 'number',
  id_agri: 'number',
  last_update: 'string',
  create_date: 'string',
  uuid: 'string',
}
