export interface ICabecalho {
  id_horario_rega: number;
  zona_homo: string;
  n_sequencia: string;
  n_subparcela: string;
  area: number;
  cenario_cli: string;
  cultura: string;
  data_sementeira: string;
  n_contador: string;
  leitura_contador_1: string;
  data_plantacao: string;
  produca_total: string;
  obtida: string;
  id_rosto: number;
  last_update: string;
  create_date: string;
  uuid: string;
}

export interface IPage6 {
  id_registo_rega: number;
  capacidade_utili: string;
  reserva_facilmente_utiliz: string;
  eficiencia_rega: string;
  mes: string;
  semana_n: string;
  date_camp_1: string;
  date_camp_2: string;
  date_camp_3: string;
  date_camp_4: string;
  date_camp_5: string;
  date_camp_6: string;
  date_camp_7: string;
  prefundidad_radi_camp_1: string;
  prefundidad_radi_camp_2: string;
  prefundidad_radi_camp_3: string;
  prefundidad_radi_camp_4: string;
  prefundidad_radi_camp_5: string;
  prefundidad_radi_camp_6: string;
  prefundidad_radi_camp_7: string;
  capacidade_campo_camp_1: string;
  capacidade_campo_camp_2: string;
  capacidade_campo_camp_3: string;
  capacidade_campo_camp_4: string;
  capacidade_campo_camp_5: string;
  capacidade_campo_camp_6: string;
  capacidade_campo_camp_7: string;
  teor_crit_cul_camp_1: string;
  teor_crit_cul_camp_2: string;
  teor_crit_cul_camp_3: string;
  teor_crit_cul_camp_4: string;
  teor_crit_cul_camp_5: string;
  teor_crit_cul_camp_6: string;
  teor_crit_cul_camp_7: string;
  teor_agua_inicio_camp_1: string;
  teor_agua_inicio_camp_2: string;
  teor_agua_inicio_camp_3: string;
  teor_agua_inicio_camp_4: string;
  teor_agua_inicio_camp_5: string;
  teor_agua_inicio_camp_6: string;
  teor_agua_inicio_camp_7: string;
  eto_camp_1: string;
  eto_camp_2: string;
  eto_camp_3: string;
  eto_camp_4: string;
  eto_camp_5: string;
  eto_camp_6: string;
  eto_camp_7: string;
  kc_camp_1: string;
  kc_camp_2: string;
  kc_camp_3: string;
  kc_camp_4: string;
  kc_camp_5: string;
  kc_camp_6: string;
  kc_camp_7: string;
  etc_camp_1: string;
  etc_camp_2: string;
  etc_camp_3: string;
  etc_camp_4: string;
  etc_camp_5: string;
  etc_camp_6: string;
  etc_camp_7: string;
  precipita_t_camp_1: string;
  precipita_t_camp_2: string;
  precipita_t_camp_3: string;
  precipita_t_camp_4: string;
  precipita_t_camp_5: string;
  precipita_t_camp_6: string;
  precipita_t_camp_7: string;
  variacao_agu_camp_1: string;
  variacao_agu_camp_2: string;
  variacao_agu_camp_3: string;
  variacao_agu_camp_4: string;
  variacao_agu_camp_5: string;
  variacao_agu_camp_6: string;
  variacao_agu_camp_7: string;
  teor_agua_solo_s_rega_camp_1: string;
  teor_agua_solo_s_rega_camp_2: string;
  teor_agua_solo_s_rega_camp_3: string;
  teor_agua_solo_s_rega_camp_4: string;
  teor_agua_solo_s_rega_camp_5: string;
  teor_agua_solo_s_rega_camp_6: string;
  teor_agua_solo_s_rega_camp_7: string;
  leitura_sonda_1_camp_1: string;
  leitura_sonda_1_camp_2: string;
  leitura_sonda_1_camp_3: string;
  leitura_sonda_1_camp_4: string;
  leitura_sonda_1_camp_5: string;
  leitura_sonda_1_camp_6: string;
  leitura_sonda_1_camp_7: string;
  leitura_sonda_2_camp_1: string;
  leitura_sonda_2_camp_2: string;
  leitura_sonda_2_camp_3: string;
  leitura_sonda_2_camp_4: string;
  leitura_sonda_2_camp_5: string;
  leitura_sonda_2_camp_6: string;
  leitura_sonda_2_camp_7: string;
  folga_prox_rega_camp_1: string;
  folga_prox_rega_camp_2: string;
  folga_prox_rega_camp_3: string;
  folga_prox_rega_camp_4: string;
  folga_prox_rega_camp_5: string;
  folga_prox_rega_camp_6: string;
  folga_prox_rega_camp_7: string;
  rega_leitura_camp_1: string;
  rega_leitura_camp_2: string;
  rega_leitura_camp_3: string;
  rega_leitura_camp_4: string;
  rega_leitura_camp_5: string;
  rega_leitura_camp_6: string;
  rega_leitura_camp_7: string;
  rega_dose_total_camp_1: string;
  rega_dose_total_camp_2: string;
  rega_dose_total_camp_3: string;
  rega_dose_total_camp_4: string;
  rega_dose_total_camp_5: string;
  rega_dose_total_camp_6: string;
  rega_dose_total_camp_7: string;
  rega_dose_util_camp_1: string;
  rega_dose_util_camp_2: string;
  rega_dose_util_camp_3: string;
  rega_dose_util_camp_4: string;
  rega_dose_util_camp_5: string;
  rega_dose_util_camp_6: string;
  rega_dose_util_camp_7: string;
  teor_agua_solo_1_camp_1: string;
  teor_agua_solo_1_camp_2: string;
  teor_agua_solo_1_camp_3: string;
  teor_agua_solo_1_camp_4: string;
  teor_agua_solo_1_camp_5: string;
  teor_agua_solo_1_camp_6: string;
  teor_agua_solo_1_camp_7: string;
  perda_agua_camp_1: string;
  perda_agua_camp_2: string;
  perda_agua_camp_3: string;
  perda_agua_camp_4: string;
  perda_agua_camp_5: string;
  perda_agua_camp_6: string;
  perda_agua_camp_7: string;
  ident_camp1: string;
  ident_camp2: string;
  ident_camp3: string;
  ident_camp4: string;
  id_horario_rega: number;
  last_update: string;
  create_date: string;
  uuid: string;
}

export const initialTable = {
  id_registo_rega: 0,
  capacidade_utili: "",
  reserva_facilmente_utiliz: "",
  eficiencia_rega: "",
  mes: "",
  semana_n: "",
  date_camp_1: "",
  date_camp_2: "",
  date_camp_3: "",
  date_camp_4: "",
  date_camp_5: "",
  date_camp_6: "",
  date_camp_7: "",
  prefundidad_radi_camp_1: "",
  prefundidad_radi_camp_2: "",
  prefundidad_radi_camp_3: "",
  prefundidad_radi_camp_4: "",
  prefundidad_radi_camp_5: "",
  prefundidad_radi_camp_6: "",
  prefundidad_radi_camp_7: "",
  capacidade_campo_camp_1: "",
  capacidade_campo_camp_2: "",
  capacidade_campo_camp_3: "",
  capacidade_campo_camp_4: "",
  capacidade_campo_camp_5: "",
  capacidade_campo_camp_6: "",
  capacidade_campo_camp_7: "",
  teor_crit_cul_camp_1: "",
  teor_crit_cul_camp_2: "",
  teor_crit_cul_camp_3: "",
  teor_crit_cul_camp_4: "",
  teor_crit_cul_camp_5: "",
  teor_crit_cul_camp_6: "",
  teor_crit_cul_camp_7: "",
  teor_agua_inicio_camp_1: "",
  teor_agua_inicio_camp_2: "",
  teor_agua_inicio_camp_3: "",
  teor_agua_inicio_camp_4: "",
  teor_agua_inicio_camp_5: "",
  teor_agua_inicio_camp_6: "",
  teor_agua_inicio_camp_7: "",
  eto_camp_1: "",
  eto_camp_2: "",
  eto_camp_3: "",
  eto_camp_4: "",
  eto_camp_5: "",
  eto_camp_6: "",
  eto_camp_7: "",
  kc_camp_1: "",
  kc_camp_2: "",
  kc_camp_3: "",
  kc_camp_4: "",
  kc_camp_5: "",
  kc_camp_6: "",
  kc_camp_7: "",
  etc_camp_1: "",
  etc_camp_2: "",
  etc_camp_3: "",
  etc_camp_4: "",
  etc_camp_5: "",
  etc_camp_6: "",
  etc_camp_7: "",
  precipita_t_camp_1: "",
  precipita_t_camp_2: "",
  precipita_t_camp_3: "",
  precipita_t_camp_4: "",
  precipita_t_camp_5: "",
  precipita_t_camp_6: "",
  precipita_t_camp_7: "",
  variacao_agu_camp_1: "",
  variacao_agu_camp_2: "",
  variacao_agu_camp_3: "",
  variacao_agu_camp_4: "",
  variacao_agu_camp_5: "",
  variacao_agu_camp_6: "",
  variacao_agu_camp_7: "",
  teor_agua_solo_s_rega_camp_1: "",
  teor_agua_solo_s_rega_camp_2: "",
  teor_agua_solo_s_rega_camp_3: "",
  teor_agua_solo_s_rega_camp_4: "",
  teor_agua_solo_s_rega_camp_5: "",
  teor_agua_solo_s_rega_camp_6: "",
  teor_agua_solo_s_rega_camp_7: "",
  leitura_sonda_1_camp_1: "",
  leitura_sonda_1_camp_2: "",
  leitura_sonda_1_camp_3: "",
  leitura_sonda_1_camp_4: "",
  leitura_sonda_1_camp_5: "",
  leitura_sonda_1_camp_6: "",
  leitura_sonda_1_camp_7: "",
  leitura_sonda_2_camp_1: "",
  leitura_sonda_2_camp_2: "",
  leitura_sonda_2_camp_3: "",
  leitura_sonda_2_camp_4: "",
  leitura_sonda_2_camp_5: "",
  leitura_sonda_2_camp_6: "",
  leitura_sonda_2_camp_7: "",
  folga_prox_rega_camp_1: "",
  folga_prox_rega_camp_2: "",
  folga_prox_rega_camp_3: "",
  folga_prox_rega_camp_4: "",
  folga_prox_rega_camp_5: "",
  folga_prox_rega_camp_6: "",
  folga_prox_rega_camp_7: "",
  rega_leitura_camp_1: "",
  rega_leitura_camp_2: "",
  rega_leitura_camp_3: "",
  rega_leitura_camp_4: "",
  rega_leitura_camp_5: "",
  rega_leitura_camp_6: "",
  rega_leitura_camp_7: "",
  rega_dose_total_camp_1: "",
  rega_dose_total_camp_2: "",
  rega_dose_total_camp_3: "",
  rega_dose_total_camp_4: "",
  rega_dose_total_camp_5: "",
  rega_dose_total_camp_6: "",
  rega_dose_total_camp_7: "",
  rega_dose_util_camp_1: "",
  rega_dose_util_camp_2: "",
  rega_dose_util_camp_3: "",
  rega_dose_util_camp_4: "",
  rega_dose_util_camp_5: "",
  rega_dose_util_camp_6: "",
  rega_dose_util_camp_7: "",
  teor_agua_solo_1_camp_1: "",
  teor_agua_solo_1_camp_2: "",
  teor_agua_solo_1_camp_3: "",
  teor_agua_solo_1_camp_4: "",
  teor_agua_solo_1_camp_5: "",
  teor_agua_solo_1_camp_6: "",
  teor_agua_solo_1_camp_7: "",
  perda_agua_camp_1: "",
  perda_agua_camp_2: "",
  perda_agua_camp_3: "",
  perda_agua_camp_4: "",
  perda_agua_camp_5: "",
  perda_agua_camp_6: "",
  perda_agua_camp_7: "",
  ident_camp1: "",
  ident_camp2: "",
  ident_camp3: "",
  ident_camp4: "",
  id_horario_rega: 0,
  last_update: "",
  create_date: "",
  uuid: "",
};


