import { ChangeEvent, useState } from "react";
import { IPage6 } from "../../../Interfaces/cadernos/caderno6";
import { Box, Stack, TableCell, TableRow } from "@mui/material";
import {
  StyledTableCell,
  StyledTableHeadLeft,
} from "../../../Styles/tabelCellStyled/customTableCell";
import { CustomTextField } from "../../../Styles/theme/customThemeprovider";
import { ButtonCadernos } from "../../../Components/barra-de-ferramentas/ButtonCadernos";
import BasicPopover from "../../../Components/Popover";

export interface INewTableRegaProps {
  tabela: IPage6 | undefined;
  setTabela: React.Dispatch<React.SetStateAction<IPage6 | undefined>>;
  updateCreateTable: () => void;
  onSaveTabela: (callback: () => void) => void;
}

export const CreateTabelaRega: React.FC<INewTableRegaProps> = ({
  tabela,
  setTabela,
  updateCreateTable,
  onSaveTabela,
}) => {
  const [error, setError] = useState<boolean>(false);
  const [messageTextField, setMessageTextField] = useState("");

  const onInputChange = (event: ChangeEvent<HTMLInputElement>) => {
    const { name, value } = event.target;
    if (name !== "eficiencia_rega" && name !== "mes" && name !== "semana_n") {
      if (isNaN(Number(value))) {
        setError(true);
        setMessageTextField("Apenas números são aceites");
        return;
      } else {
        setError(false);
        setMessageTextField("");
        Number(value);
      }
    }

    setTabela((prevOrganica:any) => ({
      ...prevOrganica,
      [name]: value,
    }));
  };

  return (
    <>
      <TableRow>
        <TableCell colSpan={8}>
          <Box sx={{ justifyContent: "end", display: "flex" }}>
            <ButtonCadernos
              mostrarBotaoGravar
              aoClicarGravar={() => onSaveTabela(updateCreateTable)}
              mostrarBotaoCancelar
              aoClicarCancelar={updateCreateTable}
            />
          </Box>
        </TableCell>
      </TableRow>
      <TableRow>
        <StyledTableHeadLeft>
          Capacidade utilizável (m3/m3):
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="capacidade_utili"
            value={tabela?.capacidade_utili}
            onChange={onInputChange}
            error={error}
            helperText={error ? messageTextField : ""}
          />
        </StyledTableHeadLeft>
        <TableCell></TableCell>
        <StyledTableHeadLeft>Eficiência da rega:</StyledTableHeadLeft>
        <TableCell></TableCell>
        <StyledTableHeadLeft> mês:</StyledTableHeadLeft>
        <TableCell></TableCell>
        <StyledTableHeadLeft> Semana n.º:</StyledTableHeadLeft>
      </TableRow>
      <TableRow>
        <StyledTableHeadLeft>
          Reserva facilmente utilizável (m3/m3):
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            value={tabela?.reserva_facilmente_utiliz}
            name="reserva_facilmente_utiliz"
            onChange={onInputChange}
            error={error}
            helperText={error ? messageTextField : ""}
          />
        </StyledTableHeadLeft>
        <TableCell></TableCell>
        <StyledTableHeadLeft>
          <CustomTextField
            value={tabela?.eficiencia_rega}
            name="eficiencia_rega"
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <TableCell></TableCell>
        <StyledTableHeadLeft>
          <CustomTextField
            name="mes"
            value={tabela?.mes}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <TableCell></TableCell>
        <StyledTableHeadLeft>
          <Stack direction="row" justifyContent="start">
            <CustomTextField
              name="semana_n"
              value={tabela?.semana_n}
              // value={tabela?.semana_n + "/" + date?.format("YYYY")}
              error={error}
              helperText={error ? messageTextField : ""}
              onChange={onInputChange}
            />
            <Box margin={-1} padding={0}>
              <BasicPopover
                text={
                  "Preencher com o n.º da semana ao qual\n diz respeito o calendário de rega e ano cívil"
                }
              />
            </Box>
          </Stack>
        </StyledTableHeadLeft>
      </TableRow>
      <TableRow>
        <TableCell></TableCell>
      </TableRow>
      <TableRow>
        <StyledTableHeadLeft>
          <Stack direction="row" justifyContent="end">
            Data
            <Box margin={-1} padding={0}>
              <BasicPopover
                text={
                  "Identificar, em cada um dos campos seguintes o dia da semana, dia do mês e mês"
                }
              />
            </Box>
          </Stack>
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>D MMM</StyledTableHeadLeft>
        <StyledTableHeadLeft>D MMM</StyledTableHeadLeft>
        <StyledTableHeadLeft>D MMM</StyledTableHeadLeft>
        <StyledTableHeadLeft>D MMM</StyledTableHeadLeft>
        <StyledTableHeadLeft>D MMM</StyledTableHeadLeft>
        <StyledTableHeadLeft>D MMM</StyledTableHeadLeft>
        <StyledTableHeadLeft>D MMM</StyledTableHeadLeft>
      </TableRow>
      <TableRow>
        <StyledTableHeadLeft>DIA DO CICLO VEGETATIVO</StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="date_camp_1"
            value={tabela?.date_camp_1}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="date_camp_2"
            value={tabela?.date_camp_2}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="date_camp_3"
            value={tabela?.date_camp_3}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="date_camp_4"
            value={tabela?.date_camp_4}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="date_camp_5"
            value={tabela?.date_camp_5}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="date_camp_6"
            value={tabela?.date_camp_6}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="date_camp_7"
            value={tabela?.date_camp_7}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
      </TableRow>
      <TableRow>
        <StyledTableHeadLeft>PROFUNDIDADE RADICULAR (m)</StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="prefundidad_radi_camp_1"
            value={tabela?.prefundidad_radi_camp_1}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="prefundidad_radi_camp_2"
            value={tabela?.prefundidad_radi_camp_2}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="prefundidad_radi_camp_3"
            value={tabela?.prefundidad_radi_camp_3}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="prefundidad_radi_camp_4"
            value={tabela?.prefundidad_radi_camp_4}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="prefundidad_radi_camp_5"
            value={tabela?.prefundidad_radi_camp_5}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="prefundidad_radi_camp_6"
            value={tabela?.prefundidad_radi_camp_6}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="prefundidad_radi_camp_7"
            value={tabela?.prefundidad_radi_camp_7}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
      </TableRow>
      <TableRow>
        <StyledTableHeadLeft>CAPACIDADE DE CAMPO (mm)</StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="capacidade_campo_camp_1"
            value={tabela?.capacidade_campo_camp_1}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="capacidade_campo_camp_2"
            value={tabela?.capacidade_campo_camp_2}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="capacidade_campo_camp_3"
            value={tabela?.capacidade_campo_camp_3}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="capacidade_campo_camp_4"
            value={tabela?.capacidade_campo_camp_4}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="capacidade_campo_camp_5"
            value={tabela?.capacidade_campo_camp_5}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="capacidade_campo_camp_6"
            value={tabela?.capacidade_campo_camp_6}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="capacidade_campo_camp_7"
            value={tabela?.capacidade_campo_camp_7}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
      </TableRow>
      <TableRow>
        <StyledTableHeadLeft>TEOR CRÍTICO CULTURAL (mm)</StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_crit_cul_camp_1"
            value={tabela?.teor_crit_cul_camp_1}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_crit_cul_camp_2"
            value={tabela?.teor_crit_cul_camp_2}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_crit_cul_camp_3"
            value={tabela?.teor_crit_cul_camp_3}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_crit_cul_camp_4"
            value={tabela?.teor_crit_cul_camp_4}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_crit_cul_camp_5"
            value={tabela?.teor_crit_cul_camp_5}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_crit_cul_camp_6"
            value={tabela?.teor_crit_cul_camp_6}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_crit_cul_camp_7"
            value={tabela?.teor_crit_cul_camp_7}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
      </TableRow>
      <TableRow>
        <StyledTableHeadLeft>
          TEOR DE ÁGUA DO SOLO - INÍCIO (mm)
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_agua_inicio_camp_1"
            value={tabela?.teor_agua_inicio_camp_1}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_agua_inicio_camp_2"
            value={tabela?.teor_agua_inicio_camp_2}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_agua_inicio_camp_3"
            value={tabela?.teor_agua_inicio_camp_3}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_agua_inicio_camp_4"
            value={tabela?.teor_agua_inicio_camp_4}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_agua_inicio_camp_5"
            value={tabela?.teor_agua_inicio_camp_5}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_agua_inicio_camp_6"
            value={tabela?.teor_agua_inicio_camp_6}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_agua_inicio_camp_7"
            value={tabela?.teor_agua_inicio_camp_7}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
      </TableRow>
      <TableRow>
        <StyledTableHeadLeft>ET0 (mm)</StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="eto_camp_1"
            value={tabela?.eto_camp_1}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="eto_camp_2"
            value={tabela?.eto_camp_2}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="eto_camp_3"
            value={tabela?.eto_camp_3}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="eto_camp_4"
            value={tabela?.eto_camp_4}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="eto_camp_5"
            value={tabela?.eto_camp_5}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="eto_camp_6"
            value={tabela?.eto_camp_6}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="eto_camp_7"
            value={tabela?.eto_camp_7}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
      </TableRow>
      <TableRow>
        <StyledTableHeadLeft>KC</StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="kc_camp_1"
            value={tabela?.kc_camp_1}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="kc_camp_2"
            value={tabela?.kc_camp_2}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="kc_camp_3"
            value={tabela?.kc_camp_3}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="kc_camp_4"
            value={tabela?.kc_camp_4}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="kc_camp_5"
            value={tabela?.kc_camp_5}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="kc_camp_6"
            value={tabela?.kc_camp_6}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="kc_camp_7"
            value={tabela?.kc_camp_7}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
      </TableRow>
      <TableRow>
        <StyledTableHeadLeft>ETC (mm)</StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="etc_camp_1"
            value={tabela?.etc_camp_1}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="etc_camp_2"
            value={tabela?.etc_camp_2}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="etc_camp_3"
            value={tabela?.etc_camp_3}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="etc_camp_4"
            value={tabela?.etc_camp_4}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="etc_camp_5"
            value={tabela?.etc_camp_5}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="etc_camp_6"
            value={tabela?.etc_camp_6}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="etc_camp_7"
            value={tabela?.etc_camp_7}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
      </TableRow>
      <TableRow>
        <StyledTableHeadLeft>PRECIPITAÇÃO TOTAL (mm)</StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="precipita_t_camp_1"
            value={tabela?.precipita_t_camp_1}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="precipita_t_camp_2"
            value={tabela?.precipita_t_camp_2}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="precipita_t_camp_3"
            value={tabela?.precipita_t_camp_3}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="precipita_t_camp_4"
            value={tabela?.precipita_t_camp_4}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="precipita_t_camp_5"
            value={tabela?.precipita_t_camp_5}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="precipita_t_camp_6"
            value={tabela?.precipita_t_camp_6}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="precipita_t_camp_7"
            value={tabela?.precipita_t_camp_7}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
      </TableRow>
      <TableRow>
        <StyledTableHeadLeft>VARIAÇÃO DA ÁGUA NO SOLO (mm)</StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="variacao_agu_camp_1"
            value={tabela?.variacao_agu_camp_1}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="variacao_agu_camp_2"
            value={tabela?.variacao_agu_camp_2}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="variacao_agu_camp_3"
            value={tabela?.variacao_agu_camp_3}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="variacao_agu_camp_4"
            value={tabela?.variacao_agu_camp_4}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="variacao_agu_camp_5"
            value={tabela?.variacao_agu_camp_5}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="variacao_agu_camp_6"
            value={tabela?.variacao_agu_camp_6}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="variacao_agu_camp_7"
            value={tabela?.variacao_agu_camp_7}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
      </TableRow>
      <TableRow>
        <StyledTableHeadLeft>
          TEOR DE ÁGUA DO SOLO - SEM REGA (mm)
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_agua_solo_s_rega_camp_1"
            value={tabela?.teor_agua_solo_s_rega_camp_1}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_agua_solo_s_rega_camp_2"
            value={tabela?.teor_agua_solo_s_rega_camp_2}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_agua_solo_s_rega_camp_3"
            value={tabela?.teor_agua_solo_s_rega_camp_3}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_agua_solo_s_rega_camp_4"
            value={tabela?.teor_agua_solo_s_rega_camp_4}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_agua_solo_s_rega_camp_5"
            value={tabela?.teor_agua_solo_s_rega_camp_5}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_agua_solo_s_rega_camp_6"
            value={tabela?.teor_agua_solo_s_rega_camp_6}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_agua_solo_s_rega_camp_7"
            value={tabela?.teor_agua_solo_s_rega_camp_7}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
      </TableRow>
      <TableRow>
        <StyledTableHeadLeft>LEITURA DA SONDA (% OU kPa)</StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="leitura_sonda_1_camp_1"
            value={tabela?.leitura_sonda_1_camp_1}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="leitura_sonda_1_camp_2"
            value={tabela?.leitura_sonda_1_camp_2}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="leitura_sonda_1_camp_3"
            value={tabela?.leitura_sonda_1_camp_3}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="leitura_sonda_1_camp_4"
            value={tabela?.leitura_sonda_1_camp_4}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="leitura_sonda_1_camp_5"
            value={tabela?.leitura_sonda_1_camp_5}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="leitura_sonda_1_camp_6"
            value={tabela?.leitura_sonda_1_camp_6}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="leitura_sonda_1_camp_7"
            value={tabela?.leitura_sonda_1_camp_7}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
      </TableRow>
      <TableRow>
        <StyledTableHeadLeft>LEITURA DA SONDA (mm)</StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="leitura_sonda_2_camp_1"
            value={tabela?.leitura_sonda_2_camp_1}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="leitura_sonda_2_camp_2"
            value={tabela?.leitura_sonda_2_camp_2}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="leitura_sonda_2_camp_3"
            value={tabela?.leitura_sonda_2_camp_3}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="leitura_sonda_2_camp_4"
            value={tabela?.leitura_sonda_2_camp_4}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="leitura_sonda_2_camp_5"
            value={tabela?.leitura_sonda_2_camp_5}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="leitura_sonda_2_camp_6"
            value={tabela?.leitura_sonda_2_camp_6}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="leitura_sonda_2_camp_7"
            value={tabela?.leitura_sonda_2_camp_7}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
      </TableRow>
      <TableRow>
        <StyledTableHeadLeft>FOLGA PARA PRÓXIMA REGA (mm)</StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="folga_prox_rega_camp_1"
            value={tabela?.folga_prox_rega_camp_1}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="folga_prox_rega_camp_2"
            value={tabela?.folga_prox_rega_camp_2}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="folga_prox_rega_camp_3"
            value={tabela?.folga_prox_rega_camp_3}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="folga_prox_rega_camp_4"
            value={tabela?.folga_prox_rega_camp_4}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="folga_prox_rega_camp_5"
            value={tabela?.folga_prox_rega_camp_5}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="folga_prox_rega_camp_6"
            value={tabela?.folga_prox_rega_camp_6}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="folga_prox_rega_camp_7"
            value={tabela?.folga_prox_rega_camp_7}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
      </TableRow>
      <TableRow>
        <StyledTableHeadLeft>
          REGA - LEITURA DO CONTADOR NO FINAL (m3)
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="rega_leitura_camp_1"
            value={tabela?.rega_leitura_camp_1}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="rega_leitura_camp_2"
            value={tabela?.rega_leitura_camp_2}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="rega_leitura_camp_3"
            value={tabela?.rega_leitura_camp_3}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="rega_leitura_camp_4"
            value={tabela?.rega_leitura_camp_4}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="rega_leitura_camp_5"
            value={tabela?.rega_leitura_camp_5}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="rega_leitura_camp_6"
            value={tabela?.rega_leitura_camp_6}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="rega_leitura_camp_7"
            value={tabela?.rega_leitura_camp_7}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
      </TableRow>
      <TableRow>
        <StyledTableHeadLeft>
          REGA - DOSE TOTAL APLICADA (mm)
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="rega_dose_total_camp_1"
            value={tabela?.rega_dose_total_camp_1}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="rega_dose_total_camp_2"
            value={tabela?.rega_dose_total_camp_2}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="rega_dose_total_camp_3"
            value={tabela?.rega_dose_total_camp_3}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="rega_dose_total_camp_4"
            value={tabela?.rega_dose_total_camp_4}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="rega_dose_total_camp_5"
            value={tabela?.rega_dose_total_camp_5}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="rega_dose_total_camp_6"
            value={tabela?.rega_dose_total_camp_6}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="rega_dose_total_camp_7"
            value={tabela?.rega_dose_total_camp_7}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
      </TableRow>
      <TableRow>
        <StyledTableHeadLeft>
          REGA - DOSE ÚTIL (mm) – APÓS REGA
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="rega_dose_util_camp_1"
            value={tabela?.rega_dose_util_camp_1}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="rega_dose_util_camp_2"
            value={tabela?.rega_dose_util_camp_2}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="rega_dose_util_camp_3"
            value={tabela?.rega_dose_util_camp_3}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="rega_dose_util_camp_4"
            value={tabela?.rega_dose_util_camp_4}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="rega_dose_util_camp_5"
            value={tabela?.rega_dose_util_camp_5}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="rega_dose_util_camp_6"
            value={tabela?.rega_dose_util_camp_6}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="rega_dose_util_camp_7"
            value={tabela?.rega_dose_util_camp_7}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
      </TableRow>
      <TableRow>
        <StyledTableHeadLeft>TEOR DE ÁGUA DO SOLO (mm)</StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_agua_solo_1_camp_1"
            value={tabela?.teor_agua_solo_1_camp_1}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_agua_solo_1_camp_2"
            value={tabela?.teor_agua_solo_1_camp_2}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_agua_solo_1_camp_3"
            value={tabela?.teor_agua_solo_1_camp_3}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_agua_solo_1_camp_4"
            value={tabela?.teor_agua_solo_1_camp_4}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_agua_solo_1_camp_5"
            value={tabela?.teor_agua_solo_1_camp_5}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_agua_solo_1_camp_6"
            value={tabela?.teor_agua_solo_1_camp_6}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="teor_agua_solo_1_camp_7"
            value={tabela?.teor_agua_solo_1_camp_7}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
      </TableRow>
      <TableRow>
        <StyledTableHeadLeft>
          PERDA DE ÁGUA (CHUVA OU REGA EXCESSIVA)
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="perda_agua_camp_1"
            value={tabela?.perda_agua_camp_1}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="perda_agua_camp_2"
            value={tabela?.perda_agua_camp_2}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="perda_agua_camp_3"
            value={tabela?.perda_agua_camp_3}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="perda_agua_camp_4"
            value={tabela?.perda_agua_camp_4}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField name="perda_agua_camp_5" onChange={onInputChange} />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="perda_agua_camp_6"
            value={tabela?.perda_agua_camp_6}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
        <StyledTableHeadLeft>
          <CustomTextField
            name="perda_agua_camp_7"
            value={tabela?.perda_agua_camp_7}
            onChange={onInputChange}
          />
        </StyledTableHeadLeft>
      </TableRow>
      <TableRow>
        <TableCell
          colSpan={4}
          sx={{
            fontWeight: 600,
            paddingTop: 10,
            fontFamily: "candara",
            fontSize: 18,
          }}
        >
          PREENCHER APENAS OS CAMPOS QUE SE APLICAM
        </TableCell>
      </TableRow>
      <TableRow>
        <TableCell sx={{ fontFamily: "candara", fontSize: 16 }}>
          IDENTIFICAÇÃO DO AVISO DE REGA com sonda (Data):
        </TableCell>
        <StyledTableCell>
          <CustomTextField
            name="ident_camp1"
            value={tabela?.ident_camp1}
            onChange={onInputChange}
          />
        </StyledTableCell>
      </TableRow>
      <TableRow>
        <TableCell sx={{ fontFamily: "candara", fontSize: 16 }}>
          IDENTIFICAÇÃO DO AVISO DE REGA com sonda (dotação recomendada m3/ha):
        </TableCell>
        <StyledTableCell>
          <CustomTextField
            name="ident_camp2"
            value={tabela?.ident_camp2}
            onChange={onInputChange}
          />
        </StyledTableCell>
      </TableRow>
      <TableRow>
        <TableCell sx={{ fontFamily: "candara", fontSize: 16 }}>
          IDENTIFICAÇÃO DO AVISO DE REGA com imagem satélite IVDI (Data):
        </TableCell>
        <StyledTableCell>
          <CustomTextField
            name="ident_camp3"
            value={tabela?.ident_camp3}
            onChange={onInputChange}
          />
        </StyledTableCell>
      </TableRow>
      <TableRow>
        <TableCell sx={{ fontFamily: "candara", fontSize: 16 }}>
          IDENTIFICAÇÃO DO AVISO DE REGA com imagem satélite IVDI (dotação
          recomendada m3/ha):
        </TableCell>
        <StyledTableCell>
          <CustomTextField
            name="ident_camp4"
            value={tabela?.ident_camp4}
            onChange={onInputChange}
          />
        </StyledTableCell>
      </TableRow>
    </>
  );
};
